MuseumProject/Models/Enums/InformationTypes.cs
namespace MuseumProject.Models.Enums
{
    public enum InformationTypes
    {
        BaseInformation = 0,
        Gallary = 1,
        Article = 2,
        News = 3,
        About = 4,
        Contacts = 5,
        Prices = 6,
        Basement = 7
    }
}

MuseumProject/Controllers/InformationController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MuseumProject.Context;
using MuseumProject.Models;

namespace MuseumProject.Controllers
{
    public class InformationController : Controller
    {
        private readonly MuseumContext _db = new MuseumContext();

        public ActionResult Index()
        {
            // TODO: удалить метод

            var informations = _db.Informations.Include(i => i.InformationType);
            return View(informations.ToList());
        }

        public ActionResult DetailsArticle(int id = 0)
        {
            //Request.UserHostAddress; - взять ip

            var information = _db.Informations.Find(id);
            if (information == null)
            {
                return HttpNotFound();
            }
        
            var model = new InformationModel(information);
            return View(model);
        }

        [HttpGet]
        public ActionResult CreateArticle()
        {
            var model = new InformationModel();
            return View("CreateArticle", model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateArticle(InformationModel model)
        {
            if (ModelState.IsValid)
            {
                var information = new Information();
                model.ApplyChange(information);

                _db.Informations.Add(information);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("CreateArticle", model);
        }

        [HttpGet]
        public ActionResult EditArticle(int id = 0)
        {
            var information = _db.Informations.Find(id);
            if (information == null)
            {
                return HttpNotFound();
            }
            ViewBag.InformationTypeId = new SelectList(_db.InformationType, "Id", "Category", information.InformationTypeId);
            var model = new InformationModel(information);
            return View("CreateArticle", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditArticle(InformationModel model)
        {
            if (ModelState.IsValid)
            {
                var information = _db.Informations.Find(model.Id);
                model.ApplyChange(information);
                _db.Entry(information).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("CreateArticle", model);
        }

        /*
        public ActionResult Delete(int id = 0)
        {
            // todo: сделать удаление
            //Information information = db.Informations.Find(id);
            //if (information == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(information);
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            // todo: сделать удаление
            //Information information = db.Informations.Find(id);
            //db.Informations.Remove(information);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }
        */


        public ActionResult DetailsNews(int id = 0)
        {
            //Request.UserHostAddress; - взять ip

            var information = _db.Informations.Find(id);
            if (information == null)
            {
                return HttpNotFound();
            }

            var model = new InformationModel(information);
            return View("DetailsArticle", model);
        }

        [HttpGet]
        public ActionResult CreateNews()
        {
            var model = new InformationModel();
            return View("CreateArticle", model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNews(InformationModel model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    //do whatever you want with the file
                }

                var information = new Information();
                model.ApplyChange(information);

                _db.Informations.Add(information);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("CreateArticle", model);
        }

        [HttpGet]
        public ActionResult EditNews(int id = 0)
        {
            var information = _db.Informations.Find(id);
            if (information == null)
            {
                return HttpNotFound();
            }
            ViewBag.InformationTypeId = new SelectList(_db.InformationType, "Id", "Category", information.InformationTypeId);
            var model = new InformationModel(information);
            return View("CreateArticle", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditNews(InformationModel model)
        {
            if (ModelState.IsValid)
            {
                var information = _db.Informations.Find(model.Id);
                model.ApplyChange(information);
                _db.Entry(information).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("CreateArticle", model);
        }


        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MuseumProject/Views/Information/CreateArticle.cshtml
@model MuseumProject.Models.ArticleModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("CreateArticle", "Information", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.Id)

    <div class="editor-label">
        @Html.LabelFor(model => model.Title)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.CreatedTime)
    </div>
    
    <div class="editor-field">
        @Html.EditorFor(model => model.CreatedTime)
        @Html.ValidationMessageFor(model => model.CreatedTime)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Text)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Text)
        @Html.ValidationMessageFor(model => model.Text)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.IsPublished)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.IsPublished)
        @Html.ValidationMessageFor(model => model.IsPublished)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.IsCommented)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.IsCommented)
        @Html.ValidationMessageFor(model => model.IsCommented)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.ShortDescription)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.ShortDescription)
        @Html.ValidationMessageFor(model => model.ShortDescription)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.InformationType)
    </div>
    <div class="editor-field">
        @Html.DropDownListFor(model => model.InformationType, Model.GetInformationTypes)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Photos)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Photos)
    </div>

    <p>
        <input type="submit" value="Save" />
    </p>
}

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

MuseumProject/Views/Information/Delete.cshtml
@model MuseumProject.Context.Information

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Information</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreatedTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreatedTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Text)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Text)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsPublished)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsPublished)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsCommented)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsCommented)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Counter)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Counter)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ShortDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ShortDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.InformationType.Category)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InformationType.Category)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MuseumProject/Views/Information/DetailsArticle.cshtml
@model MuseumProject.Models.ArticleModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Information</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>
    
    <div class="display-label">
        @Html.DisplayNameFor(model => model.InformationType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InformationType)
    </div>
    
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>
    
    <div class="display-label">
        @Html.DisplayNameFor(model => model.CreatedTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreatedTime)
    </div>
    
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Text)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Text)
    </div>
    
    <div class="display-label">
        @Html.DisplayNameFor(model => model.IsCommented)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsCommented)
    </div>
    
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Counter)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Counter)
    </div>    
</fieldset>
<p>
    @Html.ActionLink("Редактировать", "EditArticle", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MuseumProject/Views/Information/Index.cshtml
@model IEnumerable<MuseumProject.Context.Information>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Создать новую статью", "CreateArticle")
    @Html.ActionLink("Создать новость", "CreateNews")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPublished)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCommented)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Counter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InformationType.Category)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsPublished)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsCommented)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Counter)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InformationType.Category)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "EditArticle", new { id=item.Id }) |
            @Html.ActionLink("Читать далее...", "DetailsArticle", new { id=item.Id }) |
            @*@Html.ActionLink("Удалить запись", "DeleteArticle", new { id = item.Id })*@
        </td>
    </tr>
}

</table>