MuseumProject/Controllers/ArticleController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using MuseumProject.Context;
using MuseumProject.Filters;
using MuseumProject.Helpers;
using MuseumProject.Models;
using MuseumProject.Models.Abstracts;
using MuseumProject.Models.Enums;

namespace MuseumProject.Controllers
{
    [InitializeSimpleMembership]
    public class ArticleController : AbstractInformationController
    {
        private const int ArticleTypeId = (int) InformationTypes.Article;

        public ActionResult Index(int page = 1)
        {
            var itemCount = GetInformations(ArticleTypeId).Count();
            var pageCount = itemCount / ConstsHelper.PageSize + Math.Min(1, itemCount % ConstsHelper.PageSize);
            page = Math.Max(1, page);
            page = Math.Min(page, pageCount);
            var model = new AbstractInformationIndexModel
            {
                Items = GetInformations(ArticleTypeId)
                    .Skip(( page - 1 ) * ConstsHelper.PageSize)
                    .Take(ConstsHelper.PageSize)
                    .ToList()
                    .Select(i => (AbstractInformationModel) new ArticleModel(i))
                    .ToList(),
                Page = page,
                PageCount = pageCount,
                Action = "Index"
            };

            model.Items.ForEach(i => ((ArticleModel)i).Counter = _db.Counters.Count(e => e.InformationId == i.Id));
            return View(model);
        }

        public ActionResult Details(int id = 0)
        {
            var information = _db.Informations.Where(i => i.InformationTypeId == ArticleTypeId).FirstOrDefault(i => i.Id == id);
            if (information == null || !( User.IsAdmin() || information.IsPublished ))
            {
                return HttpNotFound();
            }

            UpdateCounter(id);

            var model = new ArticleModel(information);
            model.Photos = model.Photos.Where(i => i.Published).ToList();
            model.Counter = _db.Counters.Count(i => i.InformationId == id);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public ActionResult Create()
        {
            var model = new ArticleModel();
            ViewBag.ActionName = "Create";
            ViewBag.Title = "Создание статьи";
            return View("Create", model);
        }


        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleModel model)
        {
            if (ModelState.IsValid)
            {
                var information = new Information
                {
                    InformationTypeId = (int) InformationTypes.Article,
                    CreatedTime = DateTime.Now,
                    Counter = 0
                };
                model.ApplyChange(information);

                _db.Informations.Add(information);
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = information.Id });
            }
            ViewBag.ActionName = "Create";
            ViewBag.Title = "Создание статьи";
            return View("Create", model);
        }

        [HttpGet]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public ActionResult Edit(int id = 0)
        {
            var information = _db.Informations.Find(id);
            if (information == null)
            {
                return HttpNotFound();
            }
            ViewBag.InformationTypeId = new SelectList(_db.InformationType, "Id", "Category",
                information.InformationTypeId);
            var model = new ArticleModel(information);
            ViewBag.ActionName = "Edit";
            ViewBag.Title = "Изменение статьи";
            return View("Create", model);
        }

        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleModel model)
        {
            if (ModelState.IsValid)
            {
                var information = _db.Informations.Find(model.Id);
                model.ApplyChange(information);
                _db.Entry(information).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = information.Id });
            }
            ViewBag.ActionName = "Edit";
            ViewBag.Title = "Изменение статьи";
            return View("Create", model);
        }

        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public JsonResult Delete(int id)
        {
            var article = _db.Informations.Find(id);
            if (article == null || article.InformationTypeId != (int) InformationTypes.Article)
            {
                return Json(new { IsSuccess = false, Message = "Статья не найдена." });
            }

            DeteleInformation(article);
            _db.SaveChanges();

            return Json(new { IsSuccess = true, Message = "Статья успешно удалена." });
        }
    }
}

MuseumProject/Controllers/GalleryController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using MuseumProject.Context;
using MuseumProject.Filters;
using MuseumProject.Helpers;
using MuseumProject.Models;
using MuseumProject.Models.Abstracts;
using MuseumProject.Models.Enums;

namespace MuseumProject.Controllers
{
    [InitializeSimpleMembership]
    public class GalleryController : AbstractInformationController
    {
        private const int GallaryTypeId = (int) InformationTypes.Gallary;

        public ActionResult Index(int page = 1)
        {
            var itemCount = GetInformations(GallaryTypeId).Count();
            var pageCount = itemCount / ConstsHelper.PageSize + Math.Min(1, itemCount % ConstsHelper.PageSize);
            page = Math.Max(1, page);
            page = Math.Min(page, pageCount);
            var model = new AbstractInformationIndexModel
            {
                Items = GetInformations(GallaryTypeId)
                    .Skip((page - 1) * ConstsHelper.PageSize)
                    .Take(ConstsHelper.PageSize)
                    .ToList()
                    .Select(i => (AbstractInformationModel)new GalleryModel(i))
                    .ToList(),
                Page = page,
                PageCount = pageCount,
                Action = "Index"
            };

            return View(model);
        }

        public ActionResult Details(int id = 0)
        {
            var information = _db.Informations.Where(i => i.InformationTypeId == GallaryTypeId).FirstOrDefault(i => i.Id == id);
            if (information == null)
            {
                return HttpNotFound();
            }

            var model = new GalleryModel(information);
            model.Photos = model.Photos.Where(i => i.Published).ToList();
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public ActionResult Create()
        {
            var model = new GalleryModel();
            ViewBag.ActionName = "Create";
            ViewBag.Title = "Создание галереи";
            return View("Create", model);
        }


        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GalleryModel model)
        {
            if (ModelState.IsValid)
            {
                var information = new Information
                {
                    InformationTypeId = (int) InformationTypes.Gallary,
                    CreatedTime = DateTime.Now,
                    Counter = 0
                };
                model.ApplyChange(information);

                _db.Informations.Add(information);
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = information.Id });
            }
            ViewBag.ActionName = "Create";
            ViewBag.Title = "Создание галереи";
            return View("Create", model);
        }

        [HttpGet]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public ActionResult Edit(int id = 0)
        {
            var information = _db.Informations.Find(id);
            if (information == null)
            {
                return HttpNotFound();
            }
            ViewBag.InformationTypeId = new SelectList(_db.InformationType, "Id", "Category",
                information.InformationTypeId);
            var model = new GalleryModel(information);
            ViewBag.ActionName = "Edit";
            ViewBag.Title = "Изменение галереи";
            return View("Create", model);
        }

        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GalleryModel model)
        {
            if (ModelState.IsValid)
            {
                var information = _db.Informations.Find(model.Id);
                model.ApplyChange(information);
                _db.Entry(information).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = information.Id });
            }
            ViewBag.ActionName = "Edit";
            ViewBag.Title = "Изменение галереи";
            return View("Create", model);
        }

        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public JsonResult Delete(int id)
        {
            var article = _db.Informations.Find(id);
            if (article == null || article.InformationTypeId != (int) InformationTypes.Gallary)
            {
                return Json(new { IsSuccess = false, Message = "Галерея не найдена." });
            }

            DeteleInformation(article);
            _db.SaveChanges();

            return Json(new { IsSuccess = true, Message = "Галерея успешно удалена." });
        }
    }
}

MuseumProject/Controllers/NewsController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using MuseumProject.Context;
using MuseumProject.Filters;
using MuseumProject.Helpers;
using MuseumProject.Models;
using MuseumProject.Models.Abstracts;
using MuseumProject.Models.Enums;

namespace MuseumProject.Controllers
{
    [InitializeSimpleMembership]
    public class NewsController : AbstractInformationController
    {
        private const int NewsTypeId = (int) InformationTypes.News;

        public ActionResult Index(int page = 1)
        {
            var itemCount = GetInformations(NewsTypeId).Count();
            var pageCount = itemCount / ConstsHelper.PageSize + Math.Min(1, itemCount % ConstsHelper.PageSize);
            page = Math.Max(1, page);
            page = Math.Min(page, pageCount);
            var model = new AbstractInformationIndexModel
            {
                Items = GetInformations(NewsTypeId)
                    .Skip((page - 1) * ConstsHelper.PageSize)
                    .Take(ConstsHelper.PageSize)
                    .ToList()
                    .Select(i => (AbstractInformationModel)new NewsModel(i))
                    .ToList(),
                Page = page,
                PageCount = pageCount,
                Action = "Index"
            };

            model.Items.ForEach(i => ((NewsModel)i).Counter = _db.Counters.Count(e => e.InformationId == i.Id));
            return View(model);
        }

        public ActionResult Details(int id = 0)
        {
            var information = _db.Informations.Where(i => i.InformationTypeId == NewsTypeId).FirstOrDefault(i => i.Id == id);
            if (information == null || !(User.IsAdmin() || information.IsPublished))
            {
                return HttpNotFound();
            }

            UpdateCounter(id);

            var model = new NewsModel(information);
            model.Photos = model.Photos.Where(i => i.Published).ToList();
            model.Counter = _db.Counters.Count(i => i.InformationId == id);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public ActionResult Create()
        {
            var model = new NewsModel();
            ViewBag.ActionName = "Create";
            ViewBag.Title = "Создание новости";
            return View("Create", model);
        }

        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewsModel model)
        {
            if (ModelState.IsValid)
            {
                var information = new Information
                {
                    InformationTypeId = (int) InformationTypes.News,
                    CreatedTime = DateTime.Now,
                    Counter = 0
                };
                model.ApplyChange(information);

                _db.Informations.Add(information);
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = information.Id });
            }
            ViewBag.ActionName = "Create";
            ViewBag.Title = "Создание новости";
            return View("Create", model);
        }

        [HttpGet]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public ActionResult Edit(int id = 0)
        {
            var information = _db.Informations.Find(id);
            if (information == null)
            {
                return HttpNotFound();
            }
            ViewBag.InformationTypeId = new SelectList(_db.InformationType, "Id", "Category", information.InformationTypeId);
            var model = new NewsModel(information);
            ViewBag.ActionName = "Edit";
            ViewBag.Title = "Изменение новости";
            return View("Create", model);
        }

        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NewsModel model)
        {
            if (ModelState.IsValid)
            {
                var information = _db.Informations.Find(model.Id);
                model.ApplyChange(information);
                _db.Entry(information).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = information.Id });
            }
            ViewBag.ActionName = "Edit";
            ViewBag.Title = "Изменение yjdjcnb";
            return View("Create", model);
        }

        [HttpPost]
        [Authorize(Roles = ConstsHelper.AdministratorRole)]
        public JsonResult Delete(int id)
        {
            var news = _db.Informations.Find(id);
            if (news == null || news.InformationTypeId != (int)InformationTypes.News)
            {
                return Json(new { IsSuccess = false, Message = "Новость не найдена." });
            }

            DeteleInformation(news);
            _db.SaveChanges();

            return Json(new { IsSuccess = true, Message = "Новость успешно удалена." });
        }
    }
}

MuseumProject/Views/Shared/_Layout.cshtml
@using MuseumProject.Helpers
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
    @Scripts.Render("~/bundles/bootstrap")
    <title>@ViewBag.Title - Музей</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container img-rounded">
        <div class="row">
            <strong>
                <h5 style="color: #428bca; text-align: center">АЛАПАЕВСКИЙ МУЗЕЙ ИЗОБРАЗИТЕЛЬНЫХ ИСКУССТВ</h5>
            </strong>
            <!-- Carousel
      ================================================== -->
            <div id="myCarousel" class="carousel slide img-rounded" data-ride="carousel" style="margin-bottom: 0px; padding: 0px">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner img-rounded" role="listbox">
                    <div class="item active img-rounded">
                        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide" class="img-rounded">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>Певрая картинка</h1>
                                <!--<p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>-->
                                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="item img-rounded">
                        <img class="img-rounded" src="data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>Вторая картинка</h1>
                                <!--<p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>-->
                                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="item img-rounded">
                        <img class="img-rounded" src="data:image/gif;base64,R0lGODlhAQABAIAAAFVVVQAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>Третья картинка</h1>
                                <!--<p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>-->
                                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <!-- /.carousel -->

            <nav role="navigation" class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!-- Collection of nav links and other content for toggling -->
                    <div id="navbarCollapse" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Главная страница", "Index", "Home")</li>
                            <li>@Html.ActionLink("О музее", "About", "Home")</li>
                            <li>@Html.ActionLink("Статьи", "Index", "Article")</li>
                            <li>@Html.ActionLink("Новости", "Index", "News")</li>
                            <li>@Html.ActionLink("Фотогалерея", "Index", "Gallery")</li>
                            <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="row">

            <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
                @RenderSection("featured", required: false)
                @RenderBody()
            </div>

            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                <div>
                    <h3>Время работы:</h3>
                    @Html.Raw(BaseInformationHelper.GetPrices())
                </div>
                @Html.Partial("_LoginPartial")
            </div>
        </div>


        <hr />
        <footer style="background: #fff">
            @*<div class="content-wrapper">*@
            @*  <div class="float-left" style="padding-top:10px">*@
            @Html.Raw(BaseInformationHelper.GetBasement())
            @*</div>*@
            @*</div>*@
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>